class TrapspringerError(Exception):
    """Base engine error."""

class AuthorityError(TrapspringerError): ...
class KnowledgeBoundaryError(TrapspringerError): ...
class InvalidMutationError(TrapspringerError): ...
class ReplayDivergenceError(TrapspringerError): ...
class SpatialQueryError(TrapspringerError): ...
class ValidationFailureError(TrapspringerError): ...
